import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import styles from "../styles/Header.module.css";

// Navigation Link Styling
const activeLinkStyle = {
	borderBottom: "var(--link-hover-border)", // match with index.css:30
};

export default function Home() {
	const navLinks = [
		{
			to: "/",
			text: "Home",
		},
		{
			to: "/resume",
			text: "Resume",
		},
		{
			to: "/projects",
			text: "Projects",
		},
	];

	const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

	const router = useRouter();

	return (
		<>
			<Head>
				<title>Brandon Yee</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<h1 className={styles.nameHeader}>BRANDON YEE</h1>

				<nav className={styles.nav}>
					{/* Mobile Nav */}
					<div
						id="hamburger"
						style={{ position: "relative" }}
						className="hidden-desktop"
					>
						{/* eslint-disable-next-line jsx-a11y/anchor-is-valid, jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */}
						<a onClick={() => setMobileMenuOpen(!mobileMenuOpen)}>
							<span style={{ fontSize: "1.25rem" }}>Menu</span>
						</a>
						<div
							className={styles.navMobile}
							style={{
								display: mobileMenuOpen ? "block" : "none",
							}}
						>
							{navLinks.map(({ to, text }) => (
								<div className={styles.navlink} key={to}>
									<Link
										href={to}
										style={router.pathname === to ? activeLinkStyle : undefined}
										onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
									>
										{text}
									</Link>
								</div>
							))}
						</div>
					</div>

					{/* Desktop Nav */}
					<div className={`${styles.navDesktop} hidden-touch`}>
						{navLinks.map(({ to, text }) => (
							<div className={styles.navlink} key={to}>
								<Link
									href={to}
									style={router.pathname === to ? activeLinkStyle : undefined}
								>
									{text}
								</Link>
							</div>
						))}
					</div>
				</nav>
			</div>
		</>
	);
}
